# ~/.config/chezmoi/chezmoi.toml
# chmod 0600

# dell
[data]
    font_size = 10
    i3blocks_battery = "#"
    i3blocks_gputemp = ""
    i3blocks_cputemp_command = "/usr/share/i3blocks/temperature --chip coretemp-isa-0000 -c 90 -w 85"
    i3blocks_wifi = '#'

# tuxedo
[data]
    font_size = 8
    i3blocks_battery = ""
    i3blocks_gputemp = "#"
    i3blocks_cputemp_command = "/usr/share/i3blocks/temperature | head -n 1"
    i3blocks_wifi = ''
